export default {
    SET_LOADING: 'SET_LOADING',
    SET_FIRST_LOGIN: 'SET_FIRST_LOGIN',
    SET_DRAWER_CONTENT_TYPE: 'SET_DRAWER_CONTENT_TYPE',
    SET_DIGITAL_CALENDAR: 'SET_DIGITAL_CALENDAR',
    SET_FULLSCREEN_MODE: 'SET_FULLSCREEN_MODE',
    SET_DOWNLOADING_VIDEO_LIST: "SET_DOWNLOADING_VIDEO_LIST",
    ADD_DOWNLOADING_VIDEO_LIST: 'ADD_DOWNLOADING_VIDEO_LIST',
    REMOVE_DOWNLOADING_VIDEO_LIST: 'REMOVE_DOWNLOADING_VIDEO_LIST',
    SET_DATA: 'SET_DATA',
    SET_FAVORITES: 'SET_FAVORITES',
    SET_RECENT_ACTIVITY: 'SET_RECENT_ACTIVITY',
}