export default {
    SET_DEVICE_TOKEN: 'SET_DEVICE_TOKEN',     
    SET_SAVED_VIDEO_LIST: 'SET_SAVED_VIDEO_LIST',
    ADD_SAVED_VIDEO_LIST: 'ADD_SAVED_VIDEO_LIST',
    SET_APP_ORIENTATION: 'SET_APP_ORIENTATION'
}